name: unofficial_twitch_auth
description: Wrapper for the newest Twitch API for the OAuth authentication processes.
version: 0.0.2
homepage: https://www.federicoviceconti.com

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  unofficial_twitch_http: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: